### ISSUE TITLE
fix(new request): missing fields 

### ISSUE THREAD

**Issue by nijuyonkadesu** [niyasrad/CelestiDesk-BE#29]
## Bug Description
`from` and `to` date fields are missing from `/create` route.

## Steps to Reproduce

1. on [requests,route.js](https://github.com/niyasrad/CelestiDesk-BE/blob/5a0488b345f3f0232168607dee12f8b0c9930c1c/src/routes/request.routes.js#L34C50-L34C50) , the fields are missing
2. `requestDate` is not needed if we have `from` and `to`. 

## Expected Behavior
`/create` must ask for `from` and `to` dates of an request.

## Actual Behavior
![image](https://github.com/niyasrad/CelestiDesk-BE/assets/85601344/7b34ea5a-7222-407d-8e7b-ade657fe7189)

## Additional Information
- I'm just wondering if, sending `date` information as a long integer is better than plain string or not...

**Comment by niyasrad** [comment]
<img width="681" alt="image" src="https://github.com/niyasrad/CelestiDesk-BE/assets/84234554/4f06c6bb-3f90-4598-a66d-a064cba11c89">

**I'll be modifying the request body to have this format.**

- The changes shall be applied over the next PR.
- Note that, `from` and `to` are currently enabled with default date formatting, it's better to provide it with the request body, even if it's default.
