### ISSUE TITLE
fix(name): return name instead of document id

### ISSUE THREAD

**Issue by nijuyonkadesu** [niyasrad/CelestiDesk-BE#34]
## Bug Description
The name we recieve from `/pending` is a ID instead of the actual name itself.

## Steps to Reproduce

1. Simulate `/pending` after signing up in postman
2. See those received IDs instead of names

## Expected Behavior
name of the employee should be received

## Actual Behavior
![IMG_20230929_090505_563](https://github.com/niyasrad/CelestiDesk-BE/assets/85601344/92fd6867-9eeb-4863-b18a-24c470a8b442)

**Comment by niyasrad** [comment]
Thank you for the issue. Will look into this.
